services:
  pr-analyser-app:
    image: pushkargoyal/pr-analyzer
    container_name: pr-analyser-app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017
      - PORT=3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Prevent host's node_modules from overriding container's
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  mongo_data:
